### ISSUE TITLE
Code128 generator does not produce valid barcodes

### ISSUE THREAD

**Issue by schweinchendick** [graphicore/librebarcode#16] opened 2019-03-26 13:31 UTC
Using the online encoder at https://graphicore.github.io/librebarcode/ does not create valid barcodes for text with repeating digits.

**How to reproduce?** Enter `Hell222222`into the input field

**Expected** A valid barcode that decodes back to the input text

**Actual** The generated barcodes reads "Hell 666" but doesn't decode to either text. It is invalid.

Tested with "Barcode Scanner" (zxing) from Google Play Store.

**Comment by graphicore** [comment] 2019-03-26 14:14
Can you try another scanner please. It works for me with ["beep"](https://appadvice.com/app/beep-a-simple-barcode-scanner/716115660) (which apparently is no longer in the App Store) and ["Accusoft's Barcode Scanner"](https://itunes.apple.com/us/app/accusoft-barcode-scanner/id569605734?mt=8) both on IOS (via Apple App Store). This may be a faulty implementation in the app you are using. Are other barcodes scanning better in your app? It looks like especially versions with many consequent digits seem problematic.

[screenshots will follow]

What you see: the code 128 is optimizing the 22 with it's code set C symbol for `22` in the A and B set, the symbol 22 has the value of 6 and that is what is printed below. See [the table here](https://en.wikipedia.org/wiki/Code_128#Bar_code_widths) and [Barcode length optimization](https://en.wikipedia.org/wiki/Code_128#Barcode_length_optimization). The text below is not accurate in these cases. Better use a version of the font without text below, I think the text below feature has only limited usefulness.

**Comment by graphicore** [comment] 2019-03-26 15:04
Even this worked as expected, a zxing port to typescript in chromium via my laptops camera, barcode from my phone display:

https://zxing-js.github.io/library/examples/barcode-camera/

![Screenshot_2019-03-26_15-58-21](https://user-images.githubusercontent.com/393132/55007713-314e6280-4fe0-11e9-87ce-293a6cbc6dce.png)

**Comment by graphicore** [comment] 2019-03-26 15:14
Just found the zxing project has an online decoder for the original genuine java library: https://zxing.org/w/decode.jspx (via https://github.com/zxing/zxing#links)

I used the url of the image above (screenshot from Beep) `https://user-images.githubusercontent.com/393132/55004322-5049f600-4fda-11e9-95c2-96edb0e42568.png` and it worked nicely: https://zxing.org/w/decode?u=https%3A%2F%2Fuser-images.githubusercontent.com%2F393132%2F55004322-5049f600-4fda-11e9-95c2-96edb0e42568.png

![Selection_230](https://user-images.githubusercontent.com/393132/55008742-b5edb080-4fe1-11e9-8092-99bf77e48199.png)

Hence, I'm going to close this, as it does not reproduce, not even with zxing. 

If you have more remarks, feel free to re-open or just add to he discussion.

**Closed by graphicore** 2019-03-26 15:14 UTC
