### ISSUE TITLE
blank spaces

### ISSUE THREAD

**Issue by mr-k-g** [graphicore/librebarcode#41] opened 2021-03-31 08:37 UTC
Hello! The online generator (https://graphicore.github.io/librebarcode/documentation/code128) creates a string that contains the start code, 5 spaces, checksum, and the stop code (Í     "Î) for 0000000000 (10 zeroes). When your font is applied in Word to this string, nothing happens with the spaces, they remain spaces. Any hint?

**Comment by BillyDVD** [comment] 2021-04-21 18:44
Seeing the same issue - Space is actual " " not the code for space.
![image](https://user-images.githubusercontent.com/82971256/115605045-ae279580-a2a7-11eb-8f3d-666f0a5c9428.png)

**Comment by graphicore** [comment] 2021-04-21 22:48
Thanks for reporting. I'm closing this as a duplicate of #34. Please read, it has all the answers.

@BillyDVD space is actually the code for ` ` (Code A and B) and  `00`(Code C). MS-Word (and maybe others) does not do the right thing.

**Closed** 2021-04-21 22:48 UTC
