### ISSUE TITLE
Missing space glyph for Code 128 when downloaded for windows

### ISSUE THREAD

**Issue by Edwin-Maya** [graphicore/librebarcode#59] opened 2023-10-16 08:36 UTC
Hello i've tried downloading the font for windows but there is a missing glyph for the space, is there a solution to this?

**Comment by graphicore** [comment] 2023-10-20 10:36
Hi @Edwin-Maya, thanks for reporting.

Unfortunately, there's very little background information about what you are trying to achieve. The space glyph in code 128 encodes to a symbol `0` (`212222`), so space is not empty in this font. 

The font is intended to encode actual working barcodes and is following the description in https://en.wikipedia.org/wiki/Code_128#Bar_code_widths

 The font is not provisioned to separate barcodes from each other. You would rather have fields with the pure **encoded**  value set in Libre Barcode 128, e.g. using a `<span>` in HTML or a formatted table cell in a spreadsheet software. See also: https://graphicore.github.io/librebarcode/documentation/code128.html

**Comment by Biilou** [comment] 2023-10-24 14:41
Hi,
Same issue,
Codes with the space glyph work on Mac but not on Windows.
Will there be a solution ?

**Comment by graphicore** [comment] 2023-11-07 14:40
Hi @Biilou, neither from your description nor from the original description by @Edwin-Maya I get a clear idea on what the issue might be: software versions, operating system info, the input string to be rendered as a barcode and screenshots would all help.

>  Codes with the space glyph work on Mac but not on Windows.

You can use `Â` instead of the space. The display of the space code for ` ` is done by using `GSUB`, so, if the Open Type feature [`calt` (Contextual Alternates)](https://learn.microsoft.com/en-us/typography/opentype/spec/features_ae#tag-calt) is not available or not active in your application, that would be a reason. 

Here's a description on how to activate `calt` in Mircrosoft Office: 
https://github.com/graphicore/librebarcode/issues/28#issuecomment-745736391

I'm guessing this is a duplicate of:
https://github.com/graphicore/librebarcode/issues/34

**Closed by graphicore** 2023-11-07 14:40 UTC
